### ISSUE TITLE
[SUGGESTION] Port to 1.18.2?

### ISSUE THREAD

**Issue by TheRealPicasso** [ByMartrixx/SecurityCraftFabric#5]
Its recently updated to 1.19.2 (1.18.2 probably finished) so i think porting it to this version would be really great! Might be some work but I didn´t find any mod like this yet, would be amazing!

Thanks for reading my suggestion and waiting for response :)

**Comment by IotaBread** [comment]
See #2 - Port isn't finished, won't work on it

**Comment by TheRealPicasso** [comment]
Thats sad, i thought atleast its still in work... Well thanks
